[package]
name = "cowboy"
version = "0.1.7"
edition = "2024"
license = "MIT"
description = "Safe & convenient container for quick prototyping."
authors = ["Andre Popovitch <andre@popovit.ch>"]
repository = "https://github.com/anchpop/tysm"

[features]
evil = []

[dependencies]
