[package]
name = "cowboy"
version = "0.1.3"
edition = "2024"
license = "MIT"
description = "For quick prototyping."
authors = ["Andre Popovitch <andre@popovit.ch>"]
repository = "https://github.com/anchpop/tysm"


[dependencies]
